services:
  postgres:
    container_name: wm_app_postgres
    image: postgres:17
    restart: always
    env_file:
      - ./backend/envs/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres_db:/var/lib/postgresql/data

  backend:
    container_name: wm_app_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./backend/envs/.env.dev
    depends_on:
      - postgres
    entrypoint: /entrypoint.sh
    volumes:
      - ./backend/staticfiles:/home/app/backend/static_files
      - ./backend/mediafiles:/home/app/backend/mediafiles
      - ./backend/locale:/home/app/backend/locale
    platform: linux/amd64
    command: bash -c "gunicorn core.wsgi:application --bind=0.0.0.0:8000 --workers=$((2 * $(nproc) + 1))"

  frontend:
    container_name: wm_app_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./frontend/envs/.env.dev
    command: bash -c "npm run docker-build && npm run docker-start"
    depends_on:
      - backend
    
  nginx:
    container_name: wm_app_nginx
    build:
      context: .
      dockerfile: ./nginx/dev/Dockerfile
    restart: on-failure
    volumes:
      - ./backend/staticfiles:/home/app/backend/static_files
      - ./backend/mediafiles:/home/app/backend/mediafiles
      - ./backend/locale:/home/app/backend/locale
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - backend

