services:
  postgres:
    container_name: wm_app_postgres
    image: postgres:17
    restart: always
    env_file:
      - ./backend/envs/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres_db:/var/lib/postgresql/data

  backend:
    container_name: wm_app_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./backend/envs/.env.prod
    depends_on:
      - postgres
    entrypoint: /entrypoint.sh
    volumes:
      - ./backend/staticfiles:/home/app/backend/static_files
      - ./backend/mediafiles:/home/app/backend/mediafiles
      - ./backend/locale:/home/app/backend/locale
    platform: linux/amd64
    command: bash -c "gunicorn core.wsgi:application --bind=0.0.0.0:8000 --workers=$((2 * $(nproc) + 1)) --timeout=120"

  frontend:
    container_name: wm_app_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./frontend/envs/.env.prod
    command: bash -c "npm run build && npm run start"
    depends_on:
      - backend
    
  nginx:
    container_name: wm_app_nginx
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/home/app/backend/static_files
      - ./backend/mediafiles:/home/app/backend/mediafiles
      - ./backend/locale:/home/app/backend/locale
      - ./nginx/prod/conf.d:/etc/nginx/conf.d
      - ./nginx/prod/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/prod/custom_pages/50x.html:/usr/share/nginx/html/50x.html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

