services:
  postgres:
    container_name: wm_system_local_db
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - ./envs/.env
    volumes:
      - ./postgres_db:/var/lib/postgresql/data