# Generated by Django 5.1.4 on 2025-01-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfilerowdata',
            name='asset_type',
        ),
    ]
