# Generated by Django 5.1.4 on 2025-01-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingUploadedFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_route', models.CharField(max_length=30)),
                ('sr_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('outlet_name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('pos_model', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('transport_company', models.CharField(max_length=100)),
                ('date_for_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
